// Rules metadata that does not depend on runtime APIs of the linter,
// from the ESLint docs package, which is not published to npm:
// https://github.com/eslint/eslint/blob/main/docs/package.json
// Run `npm run generate/eslint-rules-metadata` after updating `eslint`.
import { writeFile } from 'node:fs/promises'
import { ESLint } from 'eslint'

interface DocumentedRule {
  name: string
}

interface RulesData {
  types: Record<string, DocumentedRule[]>
  deprecated: DocumentedRule[]
}

const isRuleArray = (value: unknown): value is DocumentedRule[] =>
  Array.isArray(value) &&
  value.every(
    (entry: unknown) =>
      typeof entry === 'object' &&
      entry !== null &&
      'name' in entry &&
      typeof entry.name === 'string',
  )

const isRulesData = (value: unknown): value is RulesData =>
  typeof value === 'object' &&
  value !== null &&
  'types' in value &&
  typeof value.types === 'object' &&
  value.types !== null &&
  Object.values(value.types).every((rules: unknown) => isRuleArray(rules)) &&
  'deprecated' in value &&
  isRuleArray(value.deprecated)

const url = `https://raw.githubusercontent.com/eslint/eslint/v${ESLint.version}/docs/src/_data/rules.json`

const response = await fetch(url)
if (!response.ok) throw new Error(`${url} responded with ${response.status}`)

const data: unknown = await response.json()
if (!isRulesData(data)) throw new Error(`unexpected shape of ${url}`)
const { types, deprecated } = data

const names = (rules: DocumentedRule[]): string[] =>
  [...new Set(rules.map(({ name }) => name))].sort()

const ruleNameLines = (ruleNames: string[]): string =>
  ruleNames.map((name) => `  '${name}',\n`).join('')

await writeFile(
  'src/test/_eslint-rules-metadata.ts',
  `// Generated by \`npm run generate/eslint-rules-metadata\`. Do not edit.

export const eslintVersion = '${ESLint.version}'

export const coreRuleNames: string[] = [
${ruleNameLines(names([...Object.values(types).flat(), ...deprecated]))}]

export const deprecatedCoreRuleNames: string[] = [
${ruleNameLines(names(deprecated))}]
`,
)
