export const rulesToConsider: Record<string, string[]> = {
  '@eslint-community/eslint-comments': [],
  // These were previously considered covered by `eslint-plugin-import`, which
  // this configuration no longer uses.
  '': ['no-duplicate-imports', 'sort-imports'],
  n: [
    'n/exports-style',
    'n/file-extension-in-import',
    'n/global-require',
    'n/hashbang',
    'n/no-extraneous-import',
    'n/no-extraneous-require',
    'n/no-missing-import',
    'n/no-missing-require',
    'n/no-mixed-requires',
    'n/no-process-env',
    'n/no-process-exit',
    'n/no-sync',
    'n/no-unpublished-bin',
    'n/no-unpublished-import',
    'n/no-unpublished-require',
    'n/no-unsupported-features/es-builtins',
    'n/no-unsupported-features/es-syntax',
    'n/no-unsupported-features/node-builtins',
    'n/prefer-global/buffer',
    'n/prefer-global/console',
    'n/prefer-global/crypto',
    'n/prefer-global/process',
    'n/prefer-global/text-decoder',
    'n/prefer-global/text-encoder',
    'n/prefer-global/timers',
    'n/prefer-global/url',
    'n/prefer-global/url-search-params',
    'n/prefer-node-protocol',
    'n/prefer-promises/dns',
    'n/prefer-promises/fs',
  ],
  promise: [],
  '@typescript-eslint': [],
}
